name: Reusable industrial_ci Workflow for ABI Compatibility Check
# author: Christoph Froehlich <christoph.froehlich@ait.ac.at>

on:
  workflow_call:
    inputs:
      ros_distro:
        description: 'ROS_DISTRO variable for industrial_ci'
        required: true
        type: string


jobs:
  reusable_abi-compatibility-ici:
    if: ${{ !(github.event_name == 'pull_request' && contains(join(github.event.pull_request.labels.*.name, ','), 'conflicts')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ros-industrial/industrial_ci@master
        env:
          DOCKER_IMAGE: ghcr.io/ros-controls/ros:${{ inputs.ros_distro }}-ubuntu-testing
          ROS_DISTRO: ${{ inputs.ros_distro }}
          ROS_REPO: testing
          ABICHECK_URL: github:${{ github.repository }}#${{ github.base_ref }}
          NOT_TEST_BUILD: true
          BASEDIR: ${{ github.workspace }}/.work
      - uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: abi-checker-report-${{ inputs.ros_distro }}
          path: ${{ github.workspace }}/.work/abicheck/${{ github.base_ref }}
